version: '3'

networks:
  neobank:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/pgdata
    ports:
      - "5433:5432"
    networks:
      - neobank
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo-bank:
    image: neobank
    build:
      context: ./neo-bank-v4
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    networks:
      - neobank
    depends_on:
      db:
        condition: service_healthy
      mongo_db_account:
        condition: service_healthy
  
  backend_transaction:
    image: backend_transaction
    build:
      context: ./backend_transaction
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    networks:
      - neobank
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    networks:
      - neobank
    depends_on:
      db:
        condition: service_healthy
  
  mongo_db_account:
    image: "mongo:5.0.0"
    restart: always
    networks:
      - neobank
    ports:
      - 27018:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5