
version: '3'

networks:
  neobank:
    external: true


services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip_all --port 27017
    ports:
      - 60000:27017
    networks:
      - neobank
